tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'

# --------------------------------------

# os tools
brew 'bash'
brew 'coreutils'
brew 'findutils'
brew 'rsync'
brew 'tldr'
brew 'tree'
brew 'wget'

# libraries/databases
brew 'mysql'
brew 'python'
brew 'ruby'

# dev tools
brew 'git'
brew 'httpie'
brew 'jq'
brew 'node'
brew 'npm'
brew 'nvm'
brew 'yarn'

# --------------------------------------

cask_args appdir: '/Applications'

# web browsers
cask 'google-chrome'
cask 'firefox'

# text editors
cask 'sublime-text'
cask 'visual-studio-code'

# system tools
cask '1password'
cask 'alfred'
cask 'bartender'
cask 'flux'
cask 'the-unarchiver'

# dev tools
cask 'coderunner'
cask 'dash'
cask 'iterm2'
cask 'nucleo'
cask 'sequel-pro'
cask 'sketch'
cask 'sourcetree'
cask 'transmit'

# media
cask 'handbrake'
cask 'vlc'

# other apps
cask 'dropbox'
cask 'slack'

# quick look plugins
# https://github.com/sindresorhus/quick-look-plugins
cask 'betterzip'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlmobi'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'suspicious-package'
cask 'webpquicklook'

# fonts
# https://github.com/caskroom/homebrew-fonts
cask 'font-bebas-neue'
cask 'font-fira-mono'
cask 'font-fira-sans'
cask 'font-hack'
cask 'font-inconsolata'
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-roboto-mono'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
cask 'font-ubuntu'
